package export

import (
	"fmt"
	"strings"
	"time"

	"shellsage/internal/branch"
)

// ExportToMarkdown generates a structured Markdown document from the active conversation path
func ExportToMarkdown(tree *branch.ConversationTree) string {
	path := tree.GetActivePath()

	var totalPrompt, totalCompletion, totalTokens int
	for _, n := range path {
		totalPrompt += n.Usage.PromptTokens
		totalCompletion += n.Usage.CompletionTokens
		totalTokens += n.Usage.TotalTokens
	}

	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("title: \"%s\"\n", tree.Title))
	sb.WriteString(fmt.Sprintf("date: %s\n", tree.CreatedAt.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("persona: \"%s\"\n", tree.PersonaID))
	sb.WriteString(fmt.Sprintf("total_tokens: %d\n", totalTokens))
	sb.WriteString("generator: ShellSage AI Assistant\n")
	sb.WriteString("---\n\n")

	sb.WriteString(fmt.Sprintf("# 💬 %s\n\n", tree.Title))
	sb.WriteString(fmt.Sprintf("> **Export Date:** %s  \n", time.Now().Format("Jan 02, 2006 15:04:05 MST")))
	sb.WriteString(fmt.Sprintf("> **Persona:** `%s`  \n", tree.PersonaID))
	sb.WriteString(fmt.Sprintf("> **Total Messages:** %d | **Total Tokens:** %d\n\n", len(path), totalTokens))

	sb.WriteString("## 📊 Token Usage Breakdown\n\n")
	sb.WriteString("| Metric | Count |\n")
	sb.WriteString("| :--- | :--- |\n")
	sb.WriteString(fmt.Sprintf("| Prompt Tokens | %d |\n", totalPrompt))
	sb.WriteString(fmt.Sprintf("| Completion Tokens | %d |\n", totalCompletion))
	sb.WriteString(fmt.Sprintf("| **Total Tokens** | **%d** |\n\n", totalTokens))
	sb.WriteString("---\n\n")

	sb.WriteString("## 🗨️ Transcript\n\n")

	for i, node := range path {
		roleHeader := "👤 **User**"
		if node.Role == "assistant" {
			modelTag := ""
			if node.Model != "" {
				modelTag = fmt.Sprintf(" *(Model: `%s`)*", node.Model)
			}
			roleHeader = fmt.Sprintf("🤖 **Assistant**%s", modelTag)
		} else if node.Role == "system" {
			roleHeader = "⚙️ **System Prompt**"
		}

		sb.WriteString(fmt.Sprintf("### Turn %d: %s\n", i+1, roleHeader))
		sb.WriteString(fmt.Sprintf("*%s*\n\n", node.Timestamp.Format("2006-01-02 15:04:05")))
		sb.WriteString(node.Content)
		sb.WriteString("\n\n---\n\n")
	}

	sb.WriteString("*Generated with [ShellSage](https://github.com/mahmud-r-farhan/ShellSage) - The Modern AI Developer CLI*\n")

	return sb.String()
}

// ExportToHTML generates a self-contained modern dark-themed HTML document
func ExportToHTML(tree *branch.ConversationTree) string {
	path := tree.GetActivePath()

	var sb strings.Builder
	sb.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	sb.WriteString("<meta charset=\"UTF-8\">\n<title>" + tree.Title + " - ShellSage Export</title>\n")
	sb.WriteString("<style>\n")
	sb.WriteString(`
		body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #0d1117; color: #c9d1d9; margin: 0; padding: 2rem; line-height: 1.6; }
		.container { max-width: 800px; margin: 0 auto; }
		h1 { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }
		.meta { background: #161b22; padding: 1rem; border-radius: 6px; border: 1px solid #30363d; margin-bottom: 2rem; font-size: 0.9rem; }
		.message { margin-bottom: 1.5rem; padding: 1.2rem; border-radius: 8px; border: 1px solid #30363d; }
		.user { background: #161b22; border-left: 4px solid #58a6ff; }
		.assistant { background: #0f1923; border-left: 4px solid #2ea043; }
		.header { font-weight: bold; margin-bottom: 0.5rem; display: flex; justify-content: space-between; font-size: 0.95rem; }
		.content { white-space: pre-wrap; font-size: 0.95rem; }
		code { background: #21262d; padding: 0.2rem 0.4rem; border-radius: 3px; font-family: monospace; }
		pre { background: #161b22; padding: 1rem; border-radius: 6px; overflow-x: auto; border: 1px solid #30363d; }
	`)
	sb.WriteString("</style>\n</head>\n<body>\n<div class=\"container\">\n")
	sb.WriteString(fmt.Sprintf("<h1>💬 %s</h1>\n", tree.Title))
	sb.WriteString(fmt.Sprintf("<div class=\"meta\"><strong>Persona:</strong> %s | <strong>Date:</strong> %s</div>\n", tree.PersonaID, tree.CreatedAt.Format("2006-01-02 15:04:05")))

	for _, node := range path {
		class := "assistant"
		icon := "🤖 Assistant"
		if node.Role == "user" {
			class = "user"
			icon = "👤 User"
		}
		sb.WriteString(fmt.Sprintf("<div class=\"message %s\">\n", class))
		sb.WriteString(fmt.Sprintf("<div class=\"header\"><span>%s</span><span>%s</span></div>\n", icon, node.Timestamp.Format("15:04:05")))
		sb.WriteString(fmt.Sprintf("<div class=\"content\">%s</div>\n", escapeHTML(node.Content)))
		sb.WriteString("</div>\n")
	}

	sb.WriteString("<p style=\"text-align:center;color:#8b949e;font-size:0.85rem;\">Generated by ShellSage AI CLI</p>\n")
	sb.WriteString("</div>\n</body>\n</html>")

	return sb.String()
}

func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
